version: '2'
services:
  rails-app:
    container_name: tapp_rails-app
    build:
      context: .
      args:
          RAILS_ENV: ${RAILS_ENV}
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      ADMINS: ${ADMINS}
    networks:
      - internal
      - external
    ports:
      - "3000:3000"
    links:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data
    networks:
      - internal

networks:
  # Names of the networks will be prefixed with project name by docker
  internal:
    driver: bridge
  external:
    driver: bridge
